# Generated by Django 5.0.4 on 2024-05-06 05:42

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import users.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(db_index=True, max_length=32, unique=True)),
                ('name_uc', models.CharField(max_length=32, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('id', models.UUIDField(default=uuid.UUID('b2dd4d7e-42ec-4d5d-a24d-17149db10764'), editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=32, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(db_index=True, max_length=32, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('id', models.UUIDField(default=uuid.UUID('2939c6b0-1448-4c83-b6bf-2d9db6f9e236'), editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('name_uc', models.CharField(max_length=32)),
                ('latitude', models.CharField(max_length=32, null=True)),
                ('longitude', models.CharField(max_length=32, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.country')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=32)),
                ('designation', models.CharField(choices=users.models.DesignationChoice.choices, db_index=True, max_length=32)),
                ('employee_id', models.CharField(db_index=True, max_length=16, unique=True)),
                ('picture', models.ImageField(null=True, upload_to='profile')),
                ('mobile', models.CharField(max_length=16, unique=True)),
                ('email', models.CharField(db_index=True, max_length=60, unique=True)),
                ('dob', models.DateField(null=True)),
                ('door_no', models.CharField(max_length=32)),
                ('street', models.CharField(max_length=64)),
                ('locality', models.CharField(max_length=32)),
                ('gender', models.CharField(choices=users.models.GenderChoice.choices, max_length=12)),
                ('passport_no', models.CharField(max_length=16, null=True, unique=True)),
                ('nationality', models.CharField(max_length=32, null=True)),
                ('marital_status', models.CharField(choices=users.models.MaritalStatusChoice.choices, max_length=16, null=True)),
                ('no_of_children', models.IntegerField(null=True)),
                ('blood_group', models.CharField(choices=users.models.BloodGroupChoice.choices, max_length=12, null=True)),
                ('social_id_no', models.CharField(max_length=16, null=True, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('reporting_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='users.city')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='users.department')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='EducationDetails',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('id', models.UUIDField(default=uuid.UUID('5c37613e-2697-4f39-8e65-d8a763d21c76'), editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(null=True)),
                ('institute_name', models.CharField(default=None, max_length=128)),
                ('percentage', models.FloatField()),
                ('course', models.CharField(max_length=64)),
                ('level', models.CharField(default=None, max_length=32, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FamilyMembers',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('id', models.UUIDField(default=uuid.UUID('46853ae2-9188-4437-8718-7cea0fc38747'), editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('relationship', models.CharField(default=None, max_length=32, null=True)),
                ('mobile', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('dob', models.DateTimeField(null=True)),
                ('is_emergency_contact', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('id', models.UUIDField(default=uuid.UUID('9b20110b-9d44-4060-acae-fb185c14c5ff'), editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('name_uc', models.CharField(max_length=32)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.country')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.state'),
        ),
        migrations.CreateModel(
            name='UserBankdetails',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('id', models.UUIDField(default=uuid.UUID('633b2198-2450-4aaf-9c21-3fccaeb88c85'), editable=False, primary_key=True, serialize=False)),
                ('bank_name', models.CharField(max_length=32)),
                ('bankaccount_no', models.CharField(max_length=40, unique=True)),
                ('ifsc', models.CharField(max_length=16, null=True)),
                ('base_branch', models.CharField(max_length=32, null=True)),
                ('pan_card', models.CharField(max_length=16, null=True)),
                ('is_company_issued', models.BooleanField(db_index=True, default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserExperience',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('id', models.UUIDField(default=uuid.UUID('7026eedb-1f71-49aa-a656-a1fceb7956d4'), editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=64)),
                ('place_of_work', models.CharField(max_length=50)),
                ('start_datetime', models.DateField(db_index=True, default=None)),
                ('end_datetime', models.DateField(db_index=True)),
                ('skills', models.CharField(max_length=512, null=True)),
                ('achievements', models.CharField(max_length=512, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
