# Generated by Django 5.0.4 on 2024-05-06 07:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6a4dbd9b-a6b0-47f8-8a4f-1269f268d964'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='department',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ab7a4185-dd3d-4737-b6c1-abfdb4e4d5eb'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='educationdetails',
            name='id',
            field=models.UUIDField(default=uuid.UUID('77616584-e2ef-4cad-b34e-97249074019f'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='familymembers',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b5a02e23-2ecd-4d28-b994-7989670a3558'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='state',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b6ede219-e7c5-45a8-ab3b-092b3f61a98f'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(max_length=24, unique=True),
        ),
        migrations.AlterField(
            model_name='userbankdetails',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4a6a723e-414d-4db1-b208-4d78d89535e9'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userexperience',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1961b223-c4f6-41a8-8698-5bd0df546e02'), editable=False, primary_key=True, serialize=False),
        ),
    ]
