# Generated by Django 5.0.4 on 2024-05-04 14:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_reporting_to_alter_city_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f42abdf1-1768-4af9-aff2-7b42881a7384'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='department',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4487222e-1266-437a-b1d8-07dbf0007808'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='educationdetails',
            name='id',
            field=models.UUIDField(default=uuid.UUID('7cadb98f-c167-4106-bafb-82bfd12d3a77'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='familymembers',
            name='id',
            field=models.UUIDField(default=uuid.UUID('36d89f91-f511-4602-96bf-4d1a6b0b7aa1'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='state',
            name='id',
            field=models.UUIDField(default=uuid.UUID('bb756230-a4a0-4c23-be56-22137d071d1b'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='userbankdetails',
            name='id',
            field=models.UUIDField(default=uuid.UUID('53af01c5-1efc-4286-9261-9c81672d9038'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userexperience',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ce24be25-ba08-409f-b2cc-362d591001fb'), editable=False, primary_key=True, serialize=False),
        ),
    ]
