# Generated by Django 5.0.4 on 2024-05-06 10:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_city_id_alter_department_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='id',
            field=models.UUIDField(default=uuid.UUID('cb0e9d64-8b3d-4f14-91a3-5cbbdddac970'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='department',
            name='id',
            field=models.UUIDField(default=uuid.UUID('5a3b0352-6ecf-4e3a-a8e6-19fbf1856376'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='educationdetails',
            name='id',
            field=models.UUIDField(default=uuid.UUID('971f1447-9866-45a6-99a5-c28b65b2d2f6'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='familymembers',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1f68e250-62d3-4463-bf51-862aec00b8e0'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='state',
            name='id',
            field=models.UUIDField(default=uuid.UUID('8798d6eb-f21a-4c27-80df-77c9a761c08b'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='userbankdetails',
            name='id',
            field=models.UUIDField(default=uuid.UUID('5d45cc41-dcfa-4c48-b1af-ef38523663cb'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userexperience',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0be78502-8461-4409-b1ef-a5469d894251'), editable=False, primary_key=True, serialize=False),
        ),
    ]
