# Generated by Django 5.0.4 on 2024-05-04 14:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_options_user_created_at_user_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d2899af6-bc3c-444a-a194-6b0ce51402c5'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='department',
            name='id',
            field=models.UUIDField(default=uuid.UUID('69df17c5-9756-427e-af83-26a2cccccdc4'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='educationdetails',
            name='id',
            field=models.UUIDField(default=uuid.UUID('41690ad6-ae93-4793-a673-0d7306f14401'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='familymembers',
            name='id',
            field=models.UUIDField(default=uuid.UUID('72c48641-2b27-4342-a3c2-3c7f0f8744f0'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='state',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0c86aa20-5cc6-4637-b9f8-23d81aea94ad'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userbankdetails',
            name='id',
            field=models.UUIDField(default=uuid.UUID('eb817910-f022-4089-9378-2cb22161ae6e'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userexperience',
            name='id',
            field=models.UUIDField(default=uuid.UUID('5ee1db5f-75ac-4c4b-86a4-01e07a57a787'), editable=False, primary_key=True, serialize=False),
        ),
    ]
