# Generated by Django 5.0.4 on 2024-05-06 10:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_city_id_alter_department_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='id',
            field=models.UUIDField(default=uuid.UUID('bbe2a540-3beb-4f16-b36d-d7ba6ba094f1'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='department',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e9138e3c-ac60-4d5f-998c-a2c092e416b1'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='educationdetails',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e7b76278-f559-420a-b6f6-19034b184b48'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='familymembers',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c6ed3188-bcee-495e-95a7-a8bc1394b8ba'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='state',
            name='id',
            field=models.UUIDField(default=uuid.UUID('117d33d9-9101-493c-af30-64656ff9d8ca'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userbankdetails',
            name='id',
            field=models.UUIDField(default=uuid.UUID('968dda61-caa1-48fd-8016-c8375063dbca'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userexperience',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6e9d9656-5edb-4046-8646-a68f0439424a'), editable=False, primary_key=True, serialize=False),
        ),
    ]
