# Generated by Django 5.0.4 on 2024-05-04 14:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_city_id_alter_department_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2d17117c-884e-4c6d-be54-d0263d0c66a1'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='department',
            name='id',
            field=models.UUIDField(default=uuid.UUID('58621326-449a-48e5-a83f-0b51ca45d30c'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='educationdetails',
            name='id',
            field=models.UUIDField(default=uuid.UUID('3edaca8f-8e85-42f1-bf54-e854bdbf2912'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='familymembers',
            name='id',
            field=models.UUIDField(default=uuid.UUID('8c7befb4-3d6f-4abb-9c14-b1db366efc0e'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='state',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1808bad6-446c-49a3-a739-0b83ced09473'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userbankdetails',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ba51e972-d51b-4f1b-a102-b7d816e43d70'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userexperience',
            name='id',
            field=models.UUIDField(default=uuid.UUID('efba51ec-65be-4701-baa3-235ee0870ab5'), editable=False, primary_key=True, serialize=False),
        ),
    ]
