# Generated by Django 5.0.4 on 2024-05-04 14:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_city_id_alter_department_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6ff21a7d-4dbb-4885-8148-e644fe9b2cea'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='department',
            name='id',
            field=models.UUIDField(default=uuid.UUID('3aa5ed4b-44c1-415b-b627-414eff83a560'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='educationdetails',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1338058a-5f6e-43ef-b33c-6bf9bd7971b5'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='familymembers',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a59ce9b4-20ef-4a1a-8829-de76686e6f13'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='state',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1e914e38-28c3-4bd8-98c6-1cb6cbfd00c8'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userbankdetails',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c12ac9a9-e313-49a7-9de9-09fb9bcd997c'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userexperience',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b1fdc5b1-c77d-4d90-8706-4845a348014a'), editable=False, primary_key=True, serialize=False),
        ),
    ]
